# Wrangler configuration for Cloudflare Pages
name = "dasurv"
compatibility_date = "2024-02-12"
compatibility_flags = ["nodejs_compat"]

# Build configuration for Pages
[build]
command = "npm run pages:build"

# Pages specific configuration
[pages]
pages_build_output_dir = ".vercel/output/static"
